feat: add project 2
adrianopratesr/onboarding-rust pull request #2
Opened 2023-10-21 19:18 UTC by adrianopratesr

Este PR adiciona o Projeto 2

2023-10-24 13:49 UTC, luisholanda requested changes

2023-10-24 13:49 UTC, luisholanda commented on src/main.rs
> +        return new_todo;
É bem incomum usarmos `return` explicitos em rust.

```suggestion
        Todo::new(todo_name)
```

2023-10-24 13:49 UTC, luisholanda commented on src/main.rs
> +        }
Essa recursão aqui ficou um pouco estranho. IMO seria melhor escrever como um loop.

2023-10-24 13:49 UTC, luisholanda commented on src/main.rs
> +        return Todo { message };
```suggestion
        Self { message }
```

2023-10-24 14:12 UTC, landreussi requested changes

2023-10-24 14:12 UTC, landreussi commented on src/main.rs
> +    fn ask_for_new_todo(&mut self) -> Todo {
Aparentemente não tem necessidade disso ser `&mut self`
```suggestion
    fn ask_for_new_todo(&self) -> Todo {
```

2023-10-24 14:12 UTC, landreussi commented on src/main.rs
> +    fn new(message: String) -> Self {
Um detalhe bem pequeno, é que essa função pode ser uma `const fn`.

2023-10-26 13:14 UTC, adrianopratesr commented on src/main.rs
> +        return new_todo;
Feito

2023-10-26 13:15 UTC, adrianopratesr commented on src/main.rs
> +        return Todo { message };
Feito

2023-10-26 17:17 UTC, adrianopratesr commented on src/main.rs
> +    fn ask_for_new_todo(&mut self) -> Todo {
Feito

2023-10-26 19:29 UTC, adrianopratesr commented on src/main.rs
> +    fn new(message: String) -> Self {
Feito

2023-10-26 19:46 UTC, adrianopratesr commented on src/main.rs
> +        }
feito

2023-10-26 19:56 UTC, landreussi approved these changes
O código LGTM só uma melhoria bem minor

2023-10-26 19:56 UTC, landreussi commented on src/main.rs
> +            }
Acho que um `match` aqui ficaria mais elegante:

```suggestion
            match response {
                "s" => break,
                "n" => {
                    println!("Tchau brigado 🙃");
                    std::process::exit(0);
                },
                _ => {
                    println!("Resposta inválida. Insira apenas 's' para sim ou 'n' para não.");
                    self.ask_if_new_todo();
                    break;
            }
```

2023-10-26 20:02 UTC, adrianopratesr commented on src/main.rs
> +        }
Feito

2023-10-26 20:07 UTC, adrianopratesr commented on src/main.rs
> +            }
De fato fica muito melhor a estrutura

2023-10-30 19:19 UTC, antoniomatiolijr approved these changes
Reviewed-for: global-approvers

2023-10-30 19:20 UTC, merged